controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

auth:
  path: /auth
  methods: ["POST"]

api_refresh_token:
  path: /api/token/refresh

api_token_invalidate:
  path: /api/token/invalidate

logout:
  path: /logout
  methods: ["POST"]
  defaults:
    _controller: App\Controller\AuthController::logout

verify:
  path: /verify
  methods: ["GET"]
  defaults:
    _controller: App\Controller\AuthController::verify

getAdminAccountByUsername:
  path: /api/admin_accounts/getAdminAccountByUsername/{username}
  methods: ["GET"]
  defaults:
    _controller: App\Controller\AdminAccountController::getAdminAccountByUsername

getPageByRoute:
  path: /api/pages/getPageByRoute/{route}
  methods: ["GET"]
  defaults:
    _controller: App\Controller\PageController::getPageByRoute

updateNavbarStatus:
  path: /api/navbars/updateNavbarStatus/{id}
  methods: ["PATCH"]
  defaults:
    _controller: App\Controller\NavbarController::updateNavbarStatus

updateSidebarStatus:
  path: /api/sidebars/updateSidebarStatus/{id}
  methods: ["PATCH"]
  defaults:
    _controller: App\Controller\SidebarController::updateSidebarStatus

updateFooterStatus:
  path: /api/footers/updateFooterStatus/{id}
  methods: ["PATCH"]
  defaults:
    _controller: App\Controller\FooterController::updateFooterStatus

updateProfile:
  path: /api/admin_accounts/updateProfile/{id}
  methods: ["PATCH"]
  defaults:
    _controller: App\Controller\AdminAccountController::updateProfile

updatePassword:
  path: /api/admin_accounts/updatePassword/{id}
  methods: ["PATCH"]
  defaults:
    _controller: App\Controller\AdminAccountController::updatePassword

updateMyPassword:
  path: /api/admin_accounts/updateMyPassword/{id}
  methods: ["PATCH"]
  defaults:
    _controller: App\Controller\AdminAccountController::updateMyPassword
