api_platform:
  show_webby: false
  title: Back office Omicron CMS API
  version: 0.2.2
  eager_loading:
    # To enable or disable eager loading.
    enabled: true
  formats:
    json: ['application/json'],
    jsonld: ['application/ld+json']
  patch_formats:
      json: ['application/merge-patch+json']
      jsonapi: ['application/vnd.api+json']
  docs_formats:
    jsonld: ["application/ld+json"]
    jsonopenapi: ["application/vnd.openapi+json"]
    html: ["text/html"]
  defaults:
    cache_headers:
      max_age: 0
      shared_max_age: 3600
      vary: ['Content-Type', 'Authorization', 'Origin']
      invalidation:
        xkey:
          glue: ', '
    stateless: true
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
  event_listeners_backward_compatibility_layer: false
  keep_legacy_inflector: false
