gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 604800
    ttl_update: false
    token_parameter_name: refreshToken
    return_expiration: true
    return_expiration_parameter_name: refresh_token_expiration
    single_use: false
    cookie:
        enabled: true
        same_site: lax               # default value
        path: /                      # default value
        domain: null                 # default value
        http_only: true              # default value
        secure: true                 # default value
        partitioned: false           # default value
        remove_token_from_body: true # default value
