lexik_jwt_authentication:
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  user_identity_field: username
  api_platform:
    enabled: false
  set_cookies:
    BEARER: ~
  token_extractors:
    # look for a token as Authorization Header
    authorization_header:
        enabled: false
        prefix:  Bearer
        name:    Authorization

    # check token in a cookie
    cookie:
        enabled: true
        name:    BEARER

    # check token in query string parameter
    query_parameter:
        enabled: false
        name:    bearer

    # check token in a cookie
    split_cookie:
        enabled: false
        cookies:
            - jwt_hp
            - jwt_s
  # remove the token from the response body when using cookies
  remove_token_from_body_when_cookies_used: true