# api/config/packages/security.yaml
security:
  # https://symfony.com/doc/current/security.html#c-hashing-passwords
  password_hashers:
    App\Entity\AdminAccount: "auto"
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    # used to reload user from session & other features (e.g. switch_user)
    users:
      entity:
        class: App\Entity\AdminAccount
        property: username

  firewalls:
    dev:
      pattern: ^/_(profiler|wdt)
      security: false
    api:
      pattern: ^/api/
      stateless: true
      provider: users
      jwt: ~
    verify:
      pattern: ^/verify
      stateless: true
      provider: users
      jwt: ~
    updateNavbarStatus:
      pattern: ^/api/navbars/updateNavbarStatus/[0-9]+$
      stateless: true
      provider: users
      jwt: ~
    updateSidebarStatus:
      pattern: ^/api/sidebars/updateSidebarStatus/[0-9]+$
      stateless: true
      provider: users
      jwt: ~
    updateFooterStatus:
      pattern: ^/api/footers/updateFooterStatus/[0-9]+$
      stateless: true
      provider: users
      jwt: ~
    main:
      json_login:
        check_path: /auth # The name in routes.yaml is enough for mapping
        username_path: username
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
  access_control:
    - { path: ^/auth, roles: PUBLIC_ACCESS }
    - { path: ^/verify, roles: IS_AUTHENTICATED_FULLY }
    - { path: '^/api/navbars/updateNavbarStatus/[0-9]+$', roles: IS_AUTHENTICATED_FULLY }
    - { path: '^/api/sidebars/updateSidebarStatus/[0-9]+$', roles: IS_AUTHENTICATED_FULLY }
    - { path: '^/api/footers/updateFooterStatus/[0-9]+$', roles: IS_AUTHENTICATED_FULLY }
